### ISSUE TITLE
[Suggestion]: Fix "Improve existing content" issue template

### ISSUE THREAD

**Issue by joey-ma** [yoyoyojoe/press-play#3]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/yoyoyojoe/press-play/blob/main/.github/ISSUE_TEMPLATE/improve-content.yml

### What part(s) of the article would you like to see updated?

The Issue Form template currently has the wrong Code of Conduct name (GitHub Docs instead of Press-Play) and wrong link as well (currently at https://github.com/yoyoyojoe/press-play/blob/main/docs/CODE_OF_CONDUCT.md).

```yml  
- type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the Press-Play project's [Code of Conduct](https://github.com/yoyoyojoe/press-play/blob/main/docs/CODE_OF_CONDUCT.md)
          required: true
```

### Additional information

```yml  
  - type: textarea
    attributes:
      label: What article / content on `press-play` is affected?
      description: Please link to the article you'd like to see updated.
    validations:
      required: true

```
